Support registering multiplatform source sets as benchmark targets
Kotlin/kotlinx-benchmark pull request #112
Opened 2023-04-28 17:27 UTC by kyay10

Fixes #111, #103, #70, #87, and #71.

This PR enables using a separate source set for benchmarks in multiplatform projects. 

This is technically a regression fix (commit b3d1f66) since previous versions of the plugin allowed registering multiplatform source sets. Now the behavior is to first attempt at finding a matching target (e.g. `"jvm"`) and if not found, we try to find a matching source set in all targets (this is fine because source sets defined within a target always have that target's name prefixed). It seems non-trivial to support source sets that have no associated compilation, mainly because the plugin needs a compilation for them.

Implementation note: I had to use `flatMap` and `find` instead of `firstNotNullOfOrNull { it.compilations.find { } }` because `firstNotNullOfOrNull` was released in a later Kotlin version than the one that Gradle uses (so it might be a good idea to update this if kotlinx-benchmark starts supporting only Gradle 8.0+)

2023-05-12 13:21 UTC, qurbonzoda commented
Hi @kyay10,
Thanks for the contribution.
Cloud you please add an integration test to make sure the feature is appropriately supported now?
It would also help to prevent such regressions in the future.

2023-05-26 14:09 UTC, kyay10 commented
@qurbonzoda All done! I had to modify the integration test infrastructure to support adding targets. All tests run and pass!

2023-06-03 06:20 UTC, kyay10 commented
@qurbonzoda would love to get a review on this PR! Currently, build.gradle logic is quite ugly because it has to manually register the source sets as benchmark targets by using internals of the library.

2023-06-07 23:49 UTC, qurbonzoda requested changes
Could you please also update the readme section: https://github.com/Kotlin/kotlinx-benchmark#separate-source-sets-for-benchmarks

2023-06-07 23:49 UTC, qurbonzoda commented on examples/kotlin-multiplatform/build.gradle
>          register("jvm") {
The comment above seems to be outdated as the name now should be a target name or a compilation default source set name

2023-06-07 23:51 UTC, qurbonzoda commented
Otherwise LGTM.

2023-06-08 20:03 UTC, merged