Integration Tests for Benchmark Configuration Options
Kotlin/kotlinx-benchmark pull request #145
Opened 2023-08-17 10:24 UTC by wldeh

Introduces a suite of integration tests to validate the behavior of various configuration options. Aims to ensure that the toolkit behaves as expected when the build script is modified.

2023-09-04 22:00 UTC, qurbonzoda requested changes

2023-09-15 03:49 UTC, wldeh commented on integration/src/test/kotlin/kotlinx/benchmark/integration/ConfigurationTest.kt
> +    fun testOutputTimeUnitConfig() {
refactored ✅

2023-09-15 03:57 UTC, wldeh commented on integration/src/test/kotlin/kotlinx/benchmark/integration/ConfigurationTest.kt
> +            assertEquals(expectedIterations, actualIterations, "Expected $expectedIterations iterations but found $actualIterations")
Addressed https://github.com/Kotlin/kotlinx-benchmark/pull/145/commits/c4938eb9b64dd874f4d6b53f2301aac5b326d7bf

2024-05-04 21:01 UTC, qurbonzoda commented
Closing this PR in favour of: https://github.com/Kotlin/kotlinx-benchmark/pull/208

2024-05-04 21:01 UTC, closed without merging