format numbers with a fixed Locale
Kotlin/kotlinx-benchmark pull request #200
Opened 2024-04-08 09:14 UTC by adam-enko

Decimal/thousands separators differ per Locale. Using the default system Locale causes [FormatTests](https://github.com/Kotlin/kotlinx-benchmark/blob/ed69605e261b45ffa5629e4a18f39a0ba1756b66/runtime/commonTest/src/kotlinx/benchmark/tests/FormatTests.kt#L7-L6) failures when the default system Locale has `,` for the decimal separator and `.` as the thousands separator (which is common in Europe).

E.g.

```
Expected :83.3333 ops/us
Actual   :83,3333 ops/us
```

2024-04-08 12:48 UTC, qurbonzoda reviewed
Does the tests fail in JS and WasmJs as well?
`Double.format` seems to use the host default locale in those targets.

2024-04-08 12:50 UTC, qurbonzoda commented on runtime/jvmMain/src/kotlinx/benchmark/Utils.kt
> +    return if (useGrouping) "%,.0${precision}f".format(Locale.US, this)
`Locale.ROOT` for a neutral locale

2024-04-08 13:00 UTC, ALikhachev requested changes
Agree with both comments. It seems like there's no direct replacement for `Locale.ROOT` in the JS implementation, so perhaps makes sense to use some fixated locale that conforms the requirements

2024-04-08 13:24 UTC, adam-enko commented
> Does the tests fail in JS and WasmJs as well? `Double.format` seems to use the host default locale in those targets.

On my machine, they both pass. It was only the JVM ones that failed.

2024-04-08 16:12 UTC, adam-enko commented
> Agree with both comments. It seems like there's no direct replacement for `Locale.ROOT` in the JS implementation, so perhaps makes sense to use some fixated locale that conforms the requirements

So you mean, instead of `d.toLocaleString(undefined, { ... } )`, instead specify a locale with the separators we want? E.g. `d.toLocaleString('en-GB', { ... } )`

2024-04-09 16:31 UTC, ALikhachev approved these changes

2024-04-09 18:26 UTC, qurbonzoda approved these changes

2024-04-10 07:48 UTC, merged