Show TeamCity build status in Kotlinx Benchmark GitHub PRs
Kotlin/kotlinx-benchmark pull request #251
Opened 2024-08-13 11:48 UTC by Badya

2024-08-13 15:03 UTC, adam-enko approved these changes
Thanks!

2024-08-14 12:38 UTC, qurbonzoda requested changes

2024-08-14 12:38 UTC, qurbonzoda commented on .teamcity/settings.kts
> -        param("bintray-user", bintrayUserName)
`settings.kts` is auto-generated by the infra plugin. Please run `./gradlew setupTeamCity --i` to make the infra plugin update the TeamCity configuration files. It should remove the deprecated bintray publishing params as well.

2024-08-14 12:38 UTC, qurbonzoda commented on .teamcity/settings.kts
> +    features {
Teamcity build configuration files are auto-generated by infra plugin. Please add any additional configurations to the `additionalConfiguration.kt` file.

You should configure `knownBuilds.buildAll` there.

2024-08-14 13:36 UTC, merged